# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4893d958639d4a462a349ee95ca3c3eaf7bdccc7e5b0d60c51e6f736a7f98e9687e743308cbd73d0a21c4eeb70040e24c13065fe823816848f10d8a3302cd66

test:
  secret_key_base: 1cdb7a640426d38faf900c64bb25a6b1f2eb76d4c6868a8bd860dfd150d0f8aa6e410f168043b4e9867919541c449912b194dbeaf0ed934c1e1be8e65b8cfe1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
